// Generated by i18nline and preact-i18nline.
import I18n from 'preact-i18nline/i18n';

I18n.supportedLocales = ['de','en','nl'];
I18n.defaultLocale = 'en';

I18n.import = locale => {
	// we use a switch here so the import statements are statically
	// analyzable. the use of import() will make build tools generate
	// separate bundles which are downloaded on-demand.
	switch (locale) {
		case 'de': return import(/* webpackChunkName: 'i18n.de' */ './de.json');
		case 'en': return import(/* webpackChunkName: 'i18n.en' */ './en.json');
		case 'nl': return import(/* webpackChunkName: 'i18n.nl' */ './nl.json');
		default: return import(/* webpackChunkName: 'i18n.default' */ './default.json');
	}
};

if ((typeof module === 'object') && module.hot) {
	module.hot.accept('./de.json', I18n.reload('de'));
	module.hot.accept('./en.json', I18n.reload('en'));
	module.hot.accept('./nl.json', I18n.reload('nl'));
	module.hot.accept('./default.json', I18n.reload('default'));
}

export default I18n;
